---
galaxy_info:
  author: Anthony Meredith
  description: An ansible role to install virtualbox
  company: DevOpsGuys
  license:  Apache
  min_ansible_version: 1.2
 
  # Below are all platforms currently available. Just uncomment
  # the ones that apply to your role. If you don't see your 
  # platform on this list, let us know and we'll get it added!
 
  platforms:
  - name: Ubuntu
    Version:
    - trusty

  # Below are all categories currently available. Just as with
  # the platforms above, uncomment those that apply to your role.
 
  categories:
  - system

dependencies: []
  
