
---

- name: Make sure dkms package is up to date
  sudo: Yes
  apt: name=dkms state=present

- name: Configure the virtualbox API repositories
  sudo: Yes
  apt_repository: repo='deb http://download.virtualbox.org/virtualbox/debian trusty contrib' state=present

- name: Configure the Oracle APT key
  apt_key: 
    url: "https://www.virtualbox.org/download/oracle_vbox.asc"
    state: present	

- name: Update repos
  sudo: Yes
  command: apt-get update

- name: Install Virtualbox
  sudo: Yes
  apt: name=virtualbox-5.0 
     state=present

